CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260312183326_init') THEN
    CREATE TYPE public.status_enum AS ENUM ('none', 'active', 'inactive', 'deleted', 'pending_of_approval');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260312183326_init') THEN
    CREATE TABLE public.users (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(100) NOT NULL,
        "Email" character varying(255) NOT NULL,
        "PasswordHash" character varying(100) NOT NULL,
        "Status" public.status_enum NOT NULL,
        CONSTRAINT "PK_users" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260312183326_init') THEN
    INSERT INTO public.users ("Id", "Email", "Name", "PasswordHash", "Status")
    VALUES (1, 'admin@local.t', 'admin', '##########', Active);
    INSERT INTO public.users ("Id", "Email", "Name", "PasswordHash", "Status")
    VALUES (2, 'guest@local.t', 'guest', '##########', Inactive);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260312183326_init') THEN
    PERFORM setval(
        pg_get_serial_sequence('public.users', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM public.users) + 1,
            nextval(pg_get_serial_sequence('public.users', 'Id'))),
        false);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260312183326_init') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260312183326_init', '10.0.5');
    END IF;
END $EF$;
COMMIT;

